runmode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: db_goapi


docker_database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: db_goapi

gormlog: true

db_default_limit: 50

jwt_secret: jwt_secret

redis:
  addr: 127.0.0.1:6379
  password:
  db: 0

default_long_url: http://www.ybren.com
base_domain: http://127.0.0.1:8080
